ExamTickets/Components/UserInfoViewComponent.cs
namespace ExamTickets.Components;

[ViewComponent]
public class UserInfoViewComponent : ViewComponent
{
    public IViewComponentResult Invoke()
    {
        if (User.Identity?.IsAuthenticated == true)
            return View("UserInfo");
        return View();
    }
}

ExamTickets/Controllers/PreparationController.cs
namespace ExamTickets.Controllers;

public class PreparationController : Controller
{
    private readonly ExamTicketsContext _Context;
    public PreparationController(ExamTicketsContext context)
    {
        _Context = context;
    }
    public IActionResult Index()
    {
        var models = _Context.Groups.Select(i => new GroupWebModel
        {
            Id = i.Id, 
            Order = i.Order, 
            Name = i.Name
        });
        return View(models);
    }
    public IActionResult Group(int id)
    {
        var models = _Context.Examens.Where(e => e.GroupId == id).Select(i => new ExamenWebModel
        {
            Id = i.Id,
            Order = i.Order,
            GroupId = i.GroupId,
            Name = i.Name,
        });
        ViewBag.GroupName = _Context.Groups.First(e => e.Id == id).Name;
        return View(models);
    }
    public IActionResult Examen(int id)
    {
        var models = _Context.Tickets.Where(e => e.ExamenId == id).Select(i => new TicketWebModel
        {
            Id = i.Id,
            ExamenId = i.ExamenId,
            TicketText = i.TicketText,
        });
        ViewBag.GroupId = _Context.Examens.First(e => e.Id == id).GroupId;
        ViewBag.GroupName = _Context.Examens.Include(i => i.Group).First(e => e.Id == id).Group.Name;
        ViewBag.ExamenName = _Context.Examens.First(e => e.Id == id).Name;
        return View(models);
    }
    public IActionResult Ticket(int id)
    {
        var models = _Context.Questions.Include(q => q.QuestionOptions).Where(e => e.TicketId == id).Select(i => new QuestionWebModel
        {
            TicketId = id,
            QuestionText = i.QuestionText,
            QuestionOptions = i.QuestionOptions.Select(o => new QuestionOptionWebModel
            {
                OptionText = o.OptionText,
                IsCorrect = o.IsCorrect,
            }),
        });
        ViewBag.ExamenId = _Context.Tickets.First(e => e.Id == id).ExamenId;
        ViewBag.ExamenName = _Context.Tickets.Include(i => i.Examen).First(e => e.Id == id).Examen.Name;
        ViewBag.TicketText = _Context.Tickets.First(e => e.Id == id).TicketText;
        return View(models);
    }


    /// <summary> Вебмодель группа </summary>
    public class GroupWebModel
    {
        public int Id { get; set; }
        public int Order { get; set; }
        /// <summary> Название группы экзаменов </summary>
        public string Name { get; set; }
    }
    /// <summary> Вебмодель экзамен </summary>
    public class ExamenWebModel
    {
        public int Id { get; set; }
        public int Order { get; set; }
        public int GroupId { get; set; }
        /// <summary> Название экзамена </summary>
        public string Name { get; set; }
    }
    /// <summary> Вебмодель билет </summary>
    public class TicketWebModel
    {
        public int Id { get; set; }
        public int ExamenId { get; set; }
        /// <summary> Билет </summary>
        public string TicketText { get; set; }
    }
    /// <summary> Вебмодель вопроса </summary>
    public class QuestionWebModel
    {
        public int TicketId { get; set; }
        public string QuestionText { get; set; }
        public IEnumerable<QuestionOptionWebModel> QuestionOptions { get; set; } =
            new List<QuestionOptionWebModel>();
    }
    /// <summary> Вебмодель варианта ответа на вопрос </summary>
    public class QuestionOptionWebModel
    {
        public string OptionText { get; set; }
        public bool IsCorrect { get; set; }
    }
}

ExamTickets/Views/Shared/Partial/_AccountLeftSidebarPartial.cshtml
<div class="border-1 shadow rounded bg-light p-1">
    <h4 class="text-center text-white bg-success p-2">Управление профилем</h4>
    <div class="accordion-flush" id="accordionInfo">
        <ul class="nav nav-pills flex-column">
            <li class="nav-item">
                <a asp-controller="Account" asp-action="Index" class="nav-link text-dark">
                    Информация по профилю
                </a>
            </li>
        </ul>
    </div>
</div>

ExamTickets/Views/Shared/Partial/_FooterPartial.cshtml
<footer class="border-top footer text-white bg-success">
    <div class="container-md">
        &copy; 2022 - kanadeiar <a class="text-light" href="https://github.com/kanadeiar/ExamTickets">github</a>
    </div>
</footer>

ExamTickets/Views/Shared/Partial/_HeaderPartial.cshtml
<header class="sticky-top">
    <nav class="navbar navbar-expand-md navbar-dark bg-success border-bottom mb-4">
        <div class="container-md">
            <a class="navbar-brand" asp-controller="Home" asp-action="Index">
                <img src="~/favicon.png" alt="Бренд" width="30" height="30" class="d-inline-block align-text-top">
                Билеты
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <partial name="Partial/_MainMenuPartial" />

                <vc:user-info/>
            </div>
        </div>
    </nav>
</header>

ExamTickets/Views/Shared/Partial/_LeftSidebarPartial.cshtml
<div class="left-sidebar">
    <h4 class="text-center text-white bg-success p-2 rounded">Подготовка</h4>
    <div class="accordion accordion-flush" id="accordionInfo">
        <ul class="nav nav-pills flex-column">
            <div class="accordion-item">
                <h2 class="accordion-header" id="showRaport">
                    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                        data-bs-target="#genreRaports" aria-expanded="false" aria-controls="genreRaports">
                        Группы экзаменов
                    </button>
                </h2>
                <div id="genreRaports" class="accordion-collapse collapse" aria-labelledby="showRaport"
                    data-bs-parent="#accordionInfo">
                    <div class="accordion-body">
                        <ul class="list-unstyled">
                            <li>
                                <a asp-controller="Preparation" asp-action="Index" class="nav-link text-dark fw-light pb-0">
                                    Все разделы
                                </a>
                            </li>
                            <li>
                                <a asp-controller="Preparation" asp-action="Group" asp-route-id="1" class="nav-link text-dark fw-light pb-0">
                                    А. Общие требования промышленной безопасности
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>

            <li class="nav-item">
                <a asp-controller="Home" asp-action="Index" class="nav-link text-dark">
                    Информация по экзаменам
                </a>
            </li>
        </ul>
    </div>
</div>

ExamTickets/Views/Shared/Partial/_MainMenuPartial.cshtml
<ul class="navbar-nav me-auto mb-2 mb-lg-0">
    <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle active" href="#" id="navbarDropdownInfo" role="button"
           data-bs-toggle="dropdown" aria-expanded="false">
            Подготовка
        </a>
        <ul class="dropdown-menu" aria-labelledby="navbarDropdownInfo">
            <li>
                <a asp-controller="Preparation" asp-action="Index" class="dropdown-item">
                    Все разделы
                </a>
            </li>
            <li>
                <a asp-controller="Preparation" asp-action="Group" asp-route-id="1" class="dropdown-item">
                    А. Общие требования промышленной безопасности
                </a>
            </li>
        </ul>
    </li>
    <li class="nav-item">
        <a class="nav-link active" asp-controller="Home" asp-action="About">О приложении</a>
    </li>
</ul>

ExamTickets/Views/Shared/Partial/_ScriptsPartial.cshtml
<script src="~/lib/jquery/jquery.min.js"></script>
<script src="~/lib/bootstrap/js/bootstrap.bundle.min.js"></script>

<environment include="Development">
    <script src="~/js/main.js" asp-append-version="true"></script>
</environment>

<environment exclude="Development">
    <script src="~/js/site.js" asp-append-version="true"></script>
</environment>

ExamTickets/Views/Shared/Partial/_StylesPartial.cshtml
<link rel="stylesheet" href="~/lib/bootstrap/css/bootstrap.min.css" />
<link rel="stylesheet" href="~/lib/font-awesome/css/all.min.css" />

<environment include="Development">
    <link href="~/css/main.css" rel="stylesheet" asp-append-version="true" />
</environment>

<environment exclude="Development">
    <link href="~/css/site.min.css" rel="stylesheet" asp-append-version="true" />
</environment>